### ISSUE TITLE
Do you use strings for colour and type? Why not enums?

### ISSUE THREAD

**Issue by codegagan** [codegagan/ChessProblem#1]
Сӏаџԁе Маятіи

**Comment by codegagan** [comment]
[Color](https://github.com/codegagan/ChessProblem/blob/master/src/main/java/com/gagan/chess/problem/Color.java) enum is already there. Type can be implemented as enum. Analyzing the impact.

**Comment by wiewioraseb** [comment]
I will take a look.

**Comment by codegagan** [comment]
@wiewioraseb , great
